# -*- coding: utf-8 -*-
"""Project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l37oop9vxwuIaVoanLn36JJ933Hs7uTV
"""

import numpy as np
import pandas as pd
import math as math
import matplotlib.pyplot as plt

columns_to_import = ['location','timestamp_corr', 'time_elapsed_days', 'air_temp', 'rel_humid', 'in_long', 'in_short'] # Replace with your desired column names
NUGnd = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/NU%20GND.csv', usecols=columns_to_import)
NEIUGnd = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/NEIU%20GND.csv', usecols=columns_to_import)
CSUGnd = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/CSU%20GND.csv', usecols=columns_to_import)

columns_to_import = ['timestamp', 'time_elapsed_days', 'Humidity (%)', 'Rain Accumulation (cm)', 'Wind Speed (km/day)'] # Replace with your desired column names
NURf = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/NU%20RF.csv', usecols=columns_to_import)
NEIURf = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/NEIU%20RF.csv', usecols=columns_to_import)
CSURf = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/CSU%20RF.csv', usecols=columns_to_import)

# Split NEIUGnd by 'location'
NEIUGnd_Turf = NEIUGnd[NEIUGnd['location'] == 'Turf'].copy()
NEIUGnd_Savannah = NEIUGnd[NEIUGnd['location'] == 'Savannah'].copy()

# Split CSUGnd by 'location'
CSUGnd_Turf = CSUGnd[CSUGnd['location'] == 'Turf'].copy()
CSUGnd_Prairie = CSUGnd[CSUGnd['location'] == 'Prairie'].copy()

NUGnd = NUGnd[NUGnd['time_elapsed_days'].diff() > 0.020].copy().reset_index(drop=True)
NEIUGnd_Savannah = NEIUGnd_Savannah[NEIUGnd_Savannah['time_elapsed_days'].diff() > 0.020].copy().reset_index(drop=True)
NEIUGnd_Turf = NEIUGnd_Turf[NEIUGnd_Turf['time_elapsed_days'].diff() > 0.020].copy().reset_index(drop=True)
CSUGnd_Prairie = CSUGnd_Prairie[CSUGnd_Prairie['time_elapsed_days'].diff() > 0.020].copy().reset_index(drop=True)
CSUGnd_Turf = CSUGnd_Turf[CSUGnd_Turf['time_elapsed_days'].diff() > 0.020].copy().reset_index(drop=True)

# Function to interpolate NaN values using linear method
def interpolate_nan(column_name):
    NUGnd[column_name] = NUGnd[column_name].interpolate(method='linear', limit_direction='both')
    NEIUGnd_Turf[column_name] = NEIUGnd_Turf[column_name].interpolate(method='linear', limit_direction='both')
    NEIUGnd_Savannah[column_name] = NEIUGnd_Savannah[column_name].interpolate(method='linear', limit_direction='both')
    CSUGnd_Prairie[column_name] = CSUGnd_Prairie[column_name].interpolate(method='linear', limit_direction='both')
    CSUGnd_Turf[column_name] = CSUGnd_Turf[column_name].interpolate(method='linear', limit_direction='both')

# Apply interpolate
interpolate_nan('air_temp')
interpolate_nan('rel_humid')
interpolate_nan('in_long')
interpolate_nan('in_short')

# Add a column for which day each measurement is from using numpy.ceil
NUGnd['day'] = np.ceil(NUGnd['time_elapsed_days'])
NEIUGnd_Turf['day'] = np.ceil(NEIUGnd_Turf['time_elapsed_days'])
NEIUGnd_Savannah['day'] = np.ceil(NEIUGnd_Savannah['time_elapsed_days'])
CSUGnd_Turf['day'] = np.ceil(CSUGnd_Turf['time_elapsed_days'])
CSUGnd_Prairie['day'] = np.ceil(CSUGnd_Prairie['time_elapsed_days'])

def calcSun(site):
  site['sunlight'] = site['in_short'] > 25
  site['sunlight_hours'] = np.diff(site['time_elapsed_days'], prepend=0)*24
  for i in range(len(site)):
    if site.loc[i, 'sunlight'] == False:
      site.loc[i, 'sunlight_hours'] = 0
  site['daily sun'] = site.groupby('day')['sunlight_hours'].transform('sum')

calcSun(NUGnd)
calcSun(NEIUGnd_Turf)
calcSun(NEIUGnd_Savannah)
calcSun(CSUGnd_Turf)
calcSun(CSUGnd_Prairie)

n_NUGnd = len(NUGnd)
n_NEIUGnd_Sav = len(NEIUGnd_Savannah)
n_NEIUGnd_Turf = len(NEIUGnd_Turf)
n_CSUGnd_Pra = len(CSUGnd_Prairie)
n_CSUGnd_Turf = len(CSUGnd_Turf)
print(n_NUGnd)
print(n_NEIUGnd_Sav)
print(n_NEIUGnd_Turf)
print(n_CSUGnd_Pra)
print(n_CSUGnd_Turf)

NURf = NURf[NURf['time_elapsed_days'].diff() > 0.018].copy().reset_index(drop=True)
NEIURf = NEIURf[NEIURf['time_elapsed_days'].diff() > 0.018].copy().reset_index(drop=True)
CSURf = CSURf[CSURf['time_elapsed_days'].diff() > 0.018].copy().reset_index(drop=True)

# Calculate 'precip_rate'
NURf['precip_rate'] = NURf['Rain Accumulation (cm)'].diff() / NURf['time_elapsed_days'].diff()
NEIURf['precip_rate'] = NEIURf['Rain Accumulation (cm)'].diff() / NEIURf['time_elapsed_days'].diff()
CSURf['precip_rate'] = CSURf['Rain Accumulation (cm)'].diff() / CSURf['time_elapsed_days'].diff()

n_NURf = len(NURf)
n_NEIURf = len(NEIURf)
n_CSURf = len(CSURf)
print(n_NURf)
print(n_NEIURf)
print(n_CSURf)

def fill_matches(target, source):
  margin = 5/(60*60*24)
  empty = 0
  for i in range(len(target)):
    t = target.loc[i,'time_elapsed_days']
    minTarg = t - margin
    maxTarg = t + margin
    potMatches = source[(source['time_elapsed_days'] >= minTarg) & (source['time_elapsed_days'] <= maxTarg)]
    if len(potMatches) > 0:
      gap = potMatches['time_elapsed_days']-t
      target.loc[i, 'Wind Speed (km/day)'] = potMatches.loc[gap.idxmin(), 'Wind Speed (km/day)']
    else:
        empty+=1

  print(empty)

fill_matches(NUGnd, NURf)
fill_matches(NEIUGnd_Savannah, NEIURf)
fill_matches(NEIUGnd_Turf, NEIURf)
fill_matches(CSUGnd_Prairie, CSURf)
fill_matches(CSUGnd_Turf, CSURf)

interpolate_nan('Wind Speed (km/day)')
NUGnd['Avg Wind Speed (km/day)'] = NUGnd.groupby('day')['Wind Speed (km/day)'].transform('mean')
NEIUGnd_Savannah['Avg Wind Speed (km/day)'] = NEIUGnd_Savannah.groupby('day')['Wind Speed (km/day)'].transform('mean')
NEIUGnd_Turf['Avg Wind Speed (km/day)'] = NEIUGnd_Turf.groupby('day')['Wind Speed (km/day)'].transform('mean')
CSUGnd_Prairie['Avg Wind Speed (km/day)'] = CSUGnd_Prairie.groupby('day')['Wind Speed (km/day)'].transform('mean')
CSUGnd_Turf['Avg Wind Speed (km/day)'] = CSUGnd_Turf.groupby('day')['Wind Speed (km/day)'].transform('mean')

def tmax(site):
  site['tmax'] = site.groupby(['day','sunlight'])['air_temp'].transform('max')

def tmin(site):
  site['tmin'] = site.groupby(['day','sunlight'])['air_temp'].transform('min')

for site in ([NUGnd, NEIUGnd_Savannah, NEIUGnd_Turf, CSUGnd_Prairie, CSUGnd_Turf]):
  tmax(site)
  tmin(site)
  site['radiation'] = site['in_long']/1e6*60*60*24

hCritA = 100
for site in ([NURf, NEIURf, CSURf]):
  site['hCritA'] = np.ones(len(site))*hCritA

NUGnd.to_excel('NU_Gnd.xlsx', index=False)
NURf.to_excel('NU_Rf.xlsx', index=False)
NEIUGnd_Savannah.to_excel('NEIU_Gnd_Sav.xlsx', index=False)
NEIUGnd_Turf.to_excel('NEIU_Gnd_Turf.xlsx', index=False)
NEIURf.to_excel('NEIU_Rf.xlsx', index=False)
CSUGnd_Prairie.to_excel('CSU_Gnd_Pra.xlsx', index=False)
CSUGnd_Turf.to_excel('CSU_Gnd_Turf.xlsx', index=False)
CSURf.to_excel('CSU_Rf.xlsx', index=False)

NU_USDA_ET_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Model.csv', skiprows=1, usecols=[0,1])
NU_CORE_ET_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Model.csv', skiprows=1, usecols=[4,5])
NEIU_USDA_ET_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Model.csv', skiprows=1, usecols=[8,9])
NEIU_CORE_ET_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Model.csv', skiprows=1, usecols=[12,13])
CSU_USDA_ET_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Model.csv', skiprows=1, usecols=[16,17])
CSU_CORE_ET_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Model.csv', skiprows=1, usecols=[20,21])
NU_USDA_Storage_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Storage_Model.csv', skiprows=1, usecols=[0,1])
NU_CORE_Storage_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Storage_Model.csv', skiprows=1, usecols=[4,5])
NEIU_USDA_Storage_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Storage_Model.csv', skiprows=1, usecols=[8,9])
NEIU_CORE_Storage_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Storage_Model.csv', skiprows=1, usecols=[12,13])
CSU_USDA_Storage_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Storage_Model.csv', skiprows=1, usecols=[16,17])
CSU_CORE_Storage_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Storage_Model.csv', skiprows=1, usecols=[20,21])
NU_USDA_Runoff_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Runoff_Model.csv', skiprows=1, usecols=[0,1])
NU_CORE_Runoff_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Runoff_Model.csv', skiprows=1, usecols=[4,5])
NEIU_USDA_Runoff_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Runoff_Model.csv', skiprows=1, usecols=[8,9])
NEIU_CORE_Runoff_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Runoff_Model.csv', skiprows=1, usecols=[12,13])
CSU_USDA_Runoff_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Runoff_Model.csv', skiprows=1, usecols=[16,17])
CSU_CORE_Runoff_Model = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/Runoff_Model.csv', skiprows=1, usecols=[20,21,22])
NU_ET_Measured = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Measured.csv', usecols=[1,3])
NEIU_ET_Measured = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Measured.csv', usecols=[1,5])
CSU_ET_Measured = pd.read_csv('https://raw.githubusercontent.com/DoodleMcGee/CEE346Proj1Data/refs/heads/main/ET_Measured.csv', usecols=[1,7])

ET_Models = [NU_USDA_ET_Model, NU_CORE_ET_Model, NEIU_USDA_ET_Model, NEIU_CORE_ET_Model, CSU_USDA_ET_Model, CSU_CORE_ET_Model]
Storage_Models = [NU_USDA_Storage_Model, NU_CORE_Storage_Model, NEIU_USDA_Storage_Model, NEIU_CORE_Storage_Model, CSU_USDA_Storage_Model, CSU_CORE_Storage_Model]
Runoff_Models = [NU_USDA_Runoff_Model, NU_CORE_Runoff_Model, NEIU_USDA_Runoff_Model, NEIU_CORE_Runoff_Model, CSU_USDA_Runoff_Model, CSU_CORE_Runoff_Model]
ET_Measured = [NU_ET_Measured, NEIU_ET_Measured, CSU_ET_Measured]

for i in range(len(ET_Models)):
    ET_Models[i] = ET_Models[i].dropna().reset_index(drop=True)
    Storage_Models[i] = Storage_Models[i].dropna().reset_index(drop=True)
    Runoff_Models[i] = Runoff_Models[i].dropna().reset_index(drop=True)

for i in range(len(ET_Measured)):
    second_column_name = ET_Measured[i].columns[1]
    ET_Measured[i][second_column_name] = ET_Measured[i][second_column_name].replace('#VALUE!', np.nan)
    ET_Measured[i][second_column_name] = pd.to_numeric(ET_Measured[i][second_column_name], errors='coerce')
    ET_Measured[i] = ET_Measured[i].dropna(subset=[second_column_name]).reset_index(drop=True)

plt.figure(figsize=(10, 6))
plt.plot(NU_USDA_ET_Model['t'], NU_USDA_ET_Model['ET (mm/d)'], label='NU site, USDA Soil Profile Model')
plt.plot(NU_CORE_ET_Model['t.1'], NU_CORE_ET_Model['ET (mm/d).1'], label='NU site, Core Soil Profile Model')
plt.plot(NU_ET_Measured['Timestamp'], NU_ET_Measured['NU ET fl. (mm/d)'], label='NU site, Measured ET')
plt.title('ET Comparison, NU Site')
plt.xlabel('Time (days)')
plt.ylabel('ET flux (mm/d)')
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(NEIU_USDA_ET_Model['t.2'], NEIU_USDA_ET_Model['ET (mm/d).2'], label='NEIU site, USDA Soil Profile Model')
plt.plot(NEIU_CORE_ET_Model['t.3'], NEIU_CORE_ET_Model['ET (mm/d).3'], label='NEIU site, Core Soil Profile Model')
plt.plot(NEIU_ET_Measured['Timestamp'], NEIU_ET_Measured['NEIU ET fl. (mm/d)'], label='NEIU site, Measured ET')
plt.title('ET Comparison, NEIU Site')
plt.xlabel('Time (days)')
plt.ylabel('ET flux (mm/d)')
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(CSU_USDA_ET_Model['t.4'], CSU_USDA_ET_Model['ET (mm/d).4'], label='CSU site, USDA Soil Profile Model')
plt.plot(CSU_CORE_ET_Model['t.5'], CSU_CORE_ET_Model['ET (mm/d).5'], label='CSU site, Core Soil Profile Model')
plt.plot(CSU_ET_Measured['Timestamp'], CSU_ET_Measured['CSU ET fl. (mm/d)'], label='CSU site, Measured ET')
plt.title('ET Comparison, CSU Site')
plt.xlabel('Time (days)')
plt.ylabel('ET flux (mm/d)')
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(NU_USDA_Storage_Model['t'], NU_USDA_Storage_Model['storage (cm)'], label='NU site, USDA Soil Profile Model')
plt.plot(NU_CORE_Storage_Model['t.1'], NU_CORE_Storage_Model['storage (cm).1'], label='NU site, Core Soil Profile Model')
plt.plot(NEIU_USDA_Storage_Model['t.2'], NEIU_USDA_Storage_Model['storage (cm).2'], label='NEIU site, USDA Soil Profile Model')
plt.plot(NEIU_CORE_Storage_Model['t.3'], NEIU_CORE_Storage_Model['storage (cm).3'], label='NEIU site, Core Soil Profile Model')
plt.plot(CSU_USDA_Storage_Model['t.4'], CSU_USDA_Storage_Model['storage (cm).4'], label='CSU site, USDA Soil Profile Model')
plt.plot(CSU_CORE_Storage_Model['t.5'], CSU_CORE_Storage_Model['storage (cm).5'], label='CSU site, Core Soil Profile Model')
plt.title('Storage Comparison')
plt.xlabel('Time (days)')
plt.ylabel('Water Storage (cm)')
plt.grid(True)
plt.legend()
plt.show()

fig, ax1 = plt.subplots(figsize=(12, 7))

ax1.plot(CSU_CORE_Runoff_Model['t.5'], CSU_CORE_Runoff_Model['flux (cm/d).5'], label='Runoff Flux', color='blue')
ax1.set_xlabel('Time (days)')
ax1.set_ylabel('Runoff Flux (cm/d)', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

ax2 = ax1.twinx()
ax2.plot(CSU_CORE_Runoff_Model['t.5'], CSU_CORE_Runoff_Model['cum. Flux (cm)'], label='Cumulative Runoff', color='red')
ax2.set_ylabel('Cumulative Runoff (cm)', color='red')
ax2.tick_params(axis='y', labelcolor='red')

plt.title('CSU Core Runoff Model')
fig.legend(loc='upper left', bbox_to_anchor=(0.125, 0.88))
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(NUGnd['time_elapsed_days'], NUGnd['air_temp'], label='NU')
plt.plot(NEIUGnd_Savannah['time_elapsed_days'], NEIUGnd_Savannah['air_temp'], label='NEIU')
plt.plot(CSUGnd_Prairie['time_elapsed_days'], CSUGnd_Prairie['air_temp'], label='CSU')
plt.title('Air Temp')
plt.xlabel('Time (days)')
plt.ylabel('Temp (C)')
plt.grid(True)
plt.legend()
plt.show()